# no_flights_ui.py
# Render-safe, GitHub-safe standalone module for displaying
# a "No Flights Available" message for Jetstream LLC.

class NoFlightsUI:
    # Generates a simple HTML page indicating no flights were found.

    def build_page(self) -> str:
        lines = []
        lines.append("<!DOCTYPE html>")
        lines.append('<html lang="en">')
        lines.append("<head>")
        lines.append('    <meta charset="UTF-8">')
        lines.append("    <title>No Flights Available - Jetstream</title>")
        lines.append("    <style>")
        lines.append("        body {")
        lines.append("            font-family: Arial, sans-serif;")
        lines.append("            background: #eef4ff;")
        lines.append("            display: flex;")
        lines.append("            justify-content: center;")
        lines.append("            align-items: center;")
        lines.append("            height: 100vh;")
        lines.append("            margin: 0;")
        lines.append("        }")
        lines.append("        .box {")
        lines.append("            background: white;")
        lines.append("            padding: 30px;")
        lines.append("            width: 420px;")
        lines.append("            border-radius: 10px;")
        lines.append("            text-align: center;")
        lines.append("            box-shadow: 0 0 12px rgba(0,0,0,0.15);")
        lines.append("        }")
        lines.append("        h2 {")
        lines.append("            color: #003366;")
        lines.append("            margin-bottom: 15px;")
        lines.append("        }")
        lines.append("        p {")
        lines.append("            color: #444;")
        lines.append("            font-size: 15px;")
        lines.append("        }")
        lines.append("        a {")
        lines.append("            display: inline-block;")
        lines.append("            margin-top: 20px;")
        lines.append("            padding: 10px 18px;")
        lines.append("            background: #003366;")
        lines.append("            color: white;")
        lines.append("            text-decoration: none;")
        lines.append("            border-radius: 6px;")
        lines.append("            font-size: 14px;")
        lines.append("        }")
        lines.append("        a:hover {")
        lines.append("            background: #0055aa;")
        lines.append("        }")
        lines.append("    </style>")
        lines.append("</head>")
        lines.append("<body>")
        lines.append('    <div class="box">')
        lines.append("        <h2>No Flights Available</h2>")
        lines.append("        <p>We could not find any flights matching your search criteria.</p>")
        lines.append('        <a href="/search">Back to Search</a>')
        lines.append("    </div>")
        lines.append("</body>")
        lines.append("</html>")

        return "\n".join(lines)
